version: '3.3'
services:
    red-do-vlc:
        image: 'riemer/mr-do-vlc:latest'
        container_name: mr-do-vlc
        volumes:
            - './tmp/music/:/tmp/music/'
            - './playlist/:/etc/playlist/'
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        ports:
            - '8082:8080'
            - '8554:8554'
        #        devices:
        #            - /dev/snd:/dev/snd
        environment:
            - DEVICE_NAME=VlcStreamer
        privileged: true
        restart: unless-stopped
    mr-do-snapserver:
        image: 'riemerk/mr-do-snapserver:latest'
        container_name: mr-do-snapserver
        volumes:
            - './etc/snapserver.conf:/etc/snapserver.conf'
            - './config/snapserver/:/root/.config/snapserver/'
            - './tmp/music/:/tmp/'
        network_mode: host
        environment:
            - DEVICE_NAME=Snapserver
            - TZ=Europe/Berlin
        restart: unless-stopped
