apiVersion: v1
kind: ConfigMap
metadata:
  name: mr-do-asound-cfgmap
  namespace: mr-do-player
  labels:
    app.kubernetes.io/name: mr-do-player
    app.kubernetes.io/component: upnp
data:
  asound.conf: |
    pcm.!default {
        type plug
        slave.pcm rate48000Hz
    }

    pcm.rate48000Hz {
        type rate
        slave {
            pcm writeFile # Direct to the plugin which will write to a file
            format S16_LE
            rate 48000
        }
    }

    pcm.writeFile {
        type file
        slave.pcm null
        file "/tmp/music/upnpfifo"
        format "raw"
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mr-do-snapserver-cfgmap
  namespace: mr-do-player
  labels:
    app.kubernetes.io/name: mr-do-player
    app.kubernetes.io/component: snapserver
data:
  snapserver.conf: |
    [server]

    [http]
    doc_root = /usr/share/snapserver/snapweb

    [tcp]

    [stream]
    stream = pipe:///tmp/music/upnpfifo?name=upnp&sampleformat=48000:16:2
    source = librespot:///librespot?name=mrSpot&devicename=mrSpot&bitrate=320&sampleformat=48000:16:2&killall=false&params=--zeroconf-port%2042661
    source = meta:///mrSpot/upnp?name=mrMusic
    sampleformat = 48000:16:2
    codec = flac

    [logging]
