apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Apply with: kubectl apply -k .
# Or:        kubectl apply -f .  (kustomize direction argocd uses automatically)
resources:
  - app.yaml
  - configmap.yaml
  - deployment.yml
  - pv.yml
  - pvc.yml
  - pdb.yml
  - service.yml
