apiVersion: v1
kind: Service
metadata:
  namespace: mr-do-player
  name: mr-do-player-service
#  annotations:
#    metallb.universe.tf/loadBalancerIPs: 192.168.0.200
spec:
  selector:
    app: mr-do-player
  type: LoadBalancer
  loadBalancerIP: 192.168.0.6
  ports:
#    - port: 43345
#      targetPort: 43345
#      protocol: UDP
#      name: upnp1
#    - port: 33503
#      targetPort: 33503
#      protocol: UDP
#      name: upnp2
    - port: 49494
      targetPort: 49494
      protocol: TCP
      name: upnp-renderer
    - port: 1900
      targetPort: 1900
      protocol: UDP
      name: upnp-simple-service-discovry-protocol
    # snapclien
    - port: 1780
      targetPort: 1780
      protocol: TCP
      name: webinterface
    - port: 1704
      targetPort: 1704
      protocol: TCP
      name: snapcast-control
    - port: 1705
      targetPort: 1705
      protocol: TCP
      name: snapcast-stream
    # libre
    - port: 42661
      targetPort: 42661
      name: libre
    - port: 4070
      targetPort: 4070
      protocol: TCP
      name: libreapp
    - port: 5353
      targetPort: 5353
      protocol: UDP
      name: libred
