apiVersion: v1
data:
  asound.conf: |
    pcm.!default {
        type plug
        slave.pcm rate48000Hz
    }

    pcm.rate48000Hz {
        type rate
        slave {
            pcm writeFile # Direct to the plugin which will write to a file
            format S16_LE
            rate 48000
        }
    }

    pcm.writeFile {
        type file
        slave.pcm null
        file "/tmp/music/upnpfifo"
        format "raw"
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-07T22:51:48Z"
  name: mr-do-asound-cfgmap
  namespace: mr-do-player
#  resourceVersion: "20357861"
#  uid: d691b545-9eed-45b1-9f95-d6e9c14c8271
