apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mr-do-player
  name: mr-do-player-pvc-data
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      usage: mr-do-player-pv-data