apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mr-do-player
  name: mr-do-player-pv-data
  labels:
#    app.kubernetes.io/instance: mr-do-player
    usage: mr-do-player-pv-data
spec:
  capacity:
    storage: 1Gi
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
#  mountOptions:
#   - hard
#   - nfsvers=4.1
  nfs:
    server: mr0.local
    path: "/srv/nfs4/homes/mr/media"
    readOnly: false
