name: Docker Image CI upnp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push mr-do-snapclient
        uses: docker/build-push-action@v4
        with:
          context: .
          file: 'mr-do-upnp/Dockerfile'
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mr-do-upnp:latest
