name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master
    - name: Build the Docker image
      file: ./Dockerfile
      run: docker buildx . --file 'mr-do-snapclient/Dockerfile' --tag riemerk/mr-do-snapclient --platform 'amd64,arm64'
